### ISSUE TITLE
Method of Payment Missing

### ISSUE THREAD

**Issue by jprasm** [davecpearce/hacs_mywatertoronto#106]
Hi davecpearce,

This integration was working great...and then I paid with the new "MyToronto Pay" method for the first time. That option is missing in your integration, so I'm unable to get it to work.

**Comment by jprasm** [comment]
Hi Dave! 
Looks like there are two websites to pay your water bill in Toronto!  When I use your link, MyToronto Pay isn't an option, so I'm getting a pop up now "You must provide the correct last payment method of the water account."

Here is the alternate website for "Utility Account Lookup" where I am able log in fine: https://www.toronto.ca/services-payments/property-taxes-utilities/utility-account-lookup/utility-account-lookup-terms-of-use/

Thoughts? Is it a matter of just adding MyToronto Pay to the integration as an option? I might have been the very first human being to pay with this method (I better check my bank to make sure it worked!)

It's a shame that this would break a perfectly find integration!

**Comment by davecpearce** [comment]
I just published v1.3.1 to add the new payment type.  

If you want to keep your history and do not want to delete the integration and add it back in, you can change the payment type to "6" in the config/.storage/core.config_entries file.  Search for "mywatertoronto". I will add this to my todo list to see if there is a way to handle this in the UI with a configuration.

Let me know if this works for you and we can close this issue.

**Comment by jprasm** [comment]
Hi Dave,

Thank you for being so responsive. I've upgraded and restarted and the "MyToronto Pay" option is there, however, I'm sad to report that it still  it still gives me the "unknown error occurred" when I try to add the integration.

I'm using the 9 digits with leading zeros for account number, and 9 + hyphen for the client number (exactly as your instructions suggest) but it still gives me the "unknown error occurred".

I'm sorry to be such a pain. Let me know if I should try anything else.

**Comment by jprasm** [comment]
Dave, it added it when I chose the "in person" option (which is not how I paid). Anyway, it's working!

**Comment by davecpearce** [comment]
Hi @jprasm 

Glad it is working for you. I will look and see if I can improve the error messages. You can turn debug on for the custom integration and see a lot of details in the HA log file.

**Comment by jprasm** [comment]
Thank you, Dave. Much appreciated. Keep up the great work.
If you ever figure out how to make these water meters integrate directly into HA (I've got one of these Aclara things attached to mine), let me know.

**Comment by jprasm** [comment]
If I can be of help, feel free to reach out (keeping in mind I'm very new at this, but also eager to learn).

**Comment by davecpearce** [comment]
I added "N/A" and "MyToronto Pay" as a Last Payment Method.

**Comment by jprasm** [comment]
Thanks Dave!
